package lab9;

import java.util.Scanner;

public class Exception extends Throwable {

    public void exceptionDemo1() { //Задание 1
        try{
            System.out.println( 2.0 / 0.0 );
        } catch ( ArithmeticException e ) {
            System.out.println("Attempted division by zero");
        }
    }
    public void exceptionDemo2() { //Задание 2
        Scanner myScanner = new Scanner( System.in );
        System.out.print( "Enter an integer ");
        String intString = myScanner.next();
        int i = Integer.parseInt(intString); System.out.println( 2 / i );
    }
    public void exceptionDemo3() { //Задание 3,4
        try {
            Scanner myScanner = new Scanner( System.in );
            System.out.print( "Enter an integer ");
            String intString = myScanner.next();
            int i = Integer.parseInt(intString); System.out.println( 2 / i );
        }
        catch (java.lang.Exception e) {
           System.err.print("error(wrong number)");
       }
        finally { //Задание 4
            System.out.println("finally");
        }
   }

    public static void main(String[] args) {
        Exception e = new Exception();
        e.exceptionDemo1();
        e.exceptionDemo2();
        e.exceptionDemo3();
    }
}
